//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-Services-SSD_SERVICE_ID_sd_j8BZQaL5g0eDM4Nl
import { Services as SSD_SERVICE_ID_sd_j8BZQaL5g0eDM4Nl } from './sd-services/Data/Services';
//CORE_REFERENCE_IMPORT-Api-SSD_SERVICE_ID_sd_BxfVMKcrHklGBPCO
import { Api as SSD_SERVICE_ID_sd_BxfVMKcrHklGBPCO } from './sd-services/Data/Api';
//CORE_REFERENCE_IMPORT-HTTPout-SSD_SERVICE_ID_sd_GWsPxmoRAeOZIzHn
import { HTTPout as SSD_SERVICE_ID_sd_GWsPxmoRAeOZIzHn } from './sd-services/Middlewares/Post/HTTPout';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-Services-SSD_SERVICE_ID_sd_j8BZQaL5g0eDM4Nl
SSD_SERVICE_ID_sd_j8BZQaL5g0eDM4Nl,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-Api-SSD_SERVICE_ID_sd_BxfVMKcrHklGBPCO
SSD_SERVICE_ID_sd_BxfVMKcrHklGBPCO,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-HTTPout-SSD_SERVICE_ID_sd_GWsPxmoRAeOZIzHn
SSD_SERVICE_ID_sd_GWsPxmoRAeOZIzHn,
];
